[build]
  command = "npm run build"  # Projenin build komutu
  publish = "public"          # Projenin yayınlanacak dizini (örneğin, build sonrası oluşturulan dosyaların bulunduğu klasör)
  
[[redirects]]  # Opsiyonel: Yönlendirme ayarları
  from = "/*"
  to = "/index.html"
  status = 200
